export const PLAN_STATUS = {
    DRAFT: "DRAFT",
    SUBMITTED: "SUBMITTED",
    APPROVED: "APPROVED",
    NEEDS_CHANGES: "NEEDS_CHANGES",
};

export const AI_STATUS = {
    CONFORME: "CONFORME",
    A_AMELIORER: "A_AMELIORER",
    NON_CONFORME: "NON_CONFORME",
};